---
name: trigger
on:
  push:
    branches:
      - "master"
  pull_request: {}

jobs:
  DoSimpleThing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: ["Adam", "Sam"]
    
    steps:
      - name: "Say hello"
        run: echo "Hello ${{ matrix.name }}"

  Finished:
    runs-on: ubuntu-latest
    steps:
      - name: All done
        run: echo "all done saying goodbye"